<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find rm_bnrobot_sim)/urdf/bngu_sentinel/common_inertia.xacro" />
    
    <!-- 关键修改：参数从 length radius → length width height（长、宽、高独立可控） -->
    <xacro:macro name="base_xacro" params="length width height">
        <link name="base_footprint" />

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />

            <origin xyz="0.0 0.0 ${height/2.0+0.055-0.008}" rpy="0 0 0" />
        </joint>

        <link name="base_link">
         
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${length} ${width} ${height}" /> <!-- 长×宽×高 -->
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </visual>

            <!-- 碰撞：与视觉尺寸一致 -->
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${length} ${width} ${height}" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </collision>
            <xacro:box_inertia m="1.0" w="${length}" h="${width}" d="${height}"/>
        </link>
    </xacro:macro>
</robot>