<?xml version="1.0" encoding="UTF-8"?>
<robot name="bnbot" xmlns:xacro="http://ros.org/wiki/xacro" ns="bnbot">

  <!-- 1. 提取可配置参数（后续修改直接改这里，无需动结构） -->
  <xacro:property name="M_PI" value="3.1415926" />  <!-- 通用常量 -->
  
  <!-- 底座参数 -->
  <xacro:property name="base_length" value="0.633" />  <!-- 长(x) -->
  <xacro:property name="base_width" value="0.526" />   <!-- 宽(y) -->
  <xacro:property name="base_height" value="0.42" />   <!-- 高(z) -->
  <xacro:property name="base_mass" value="5.0" />      <!-- 质量(kg) -->
  <xacro:property name="base_center_z" value="${base_height/2}" />  <!-- 底座中心z坐标（自动计算，避免硬编码） -->
  
  <!-- 雷达安装参数 -->
  <xacro:property name="lidar_install_z" value="${base_height}" />  <!-- 雷达安装在底座上表面（z=底座总高度） -->
  <xacro:property name="lidar_topic" value="mid360" />  <!-- 雷达发布话题（与之前配置一致） -->

  <!-- 2. 地面参考帧（不变） -->
  <link name="base_footprint" />
  
  <!-- 3. 核心底座（使用参数化配置） -->
  <link name="base_link">
    <visual>
      <!-- 用参数替代硬编码，中心z坐标自动计算 -->
      <origin xyz="0 0 ${base_center_z}" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />  <!-- 参数化尺寸 -->
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.1 1.0 0.5" />
      </material>
    </visual>
    
    <!-- 碰撞体与视觉体一致（参数化） -->
    <collision>
      <origin xyz="0 0 ${base_center_z}" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    
    <!-- 惯性参数（参数化质量） -->
    <inertial>
      <mass value="${base_mass}" />  <!-- 用参数替代硬编码 -->
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0" izz="0.02" /> <!-- 简化惯性矩阵，可根据实际优化 -->
    </inertial>
  </link>
  
  <!-- 4. base_footprint到base_link的固定关节（参数化z轴高度） -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0.0 0.0 ${base_center_z}" rpy="0 0 0" />  <!-- z=底座中心高度（下表面贴地） -->
  </joint>

  <!-- 5. 集成Livox Mid360激光雷达（保持原有宏调用，参数化配置） -->
  <!-- 包含Mid360的xacro文件（确保ros2_livox_simulation功能包已编译安装） -->
  <xacro:include filename="$(find ros2_livox_simulation)/urdf/mid360.xacro" />
  
  <!-- 调用Mid360宏：使用参数化安装位置和话题 -->
  <xacro:mid360 name="mid360" parent="base_link" topic="${lidar_topic}" >
    <origin xyz="0 0 ${lidar_install_z}" rpy="0 0 0"/>
  </xacro:mid360>

</robot>
